language: node_js
node_js:
  - "6.10.2"
branches:
  only:
    - master
before_script:
  - npm install -g yarn
  - yarn global add karma-cli
  - yarn install
  - yarn global add codecov
script:
  - yarn test
  - yarn report-coverage
